apiVersion: v1
kind: Service
metadata:
  name: hera-nginx
  namespace: hera-namespace
spec:
  ports:
    - port: 80
      targetPort: 7001
      protocol: TCP
      nodePort: 32000
  selector:
    app: hera-nginx-fe
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: tpc-nginx
  namespace: hera-namespace
spec:
  ports:
    - port: 80
      targetPort: 7001
      protocol: TCP
      nodePort: 32001
  selector:
    app: tpc-nginx-fe
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: tpclogin-nginx
  namespace: hera-namespace
spec:
  ports:
    - port: 80
      targetPort: 7001
      protocol: TCP
      nodePort: 32002
  selector:
    app: tpclogin-nginx-fe
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: hera-namespace
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      nodePort: 32003
  selector:
    app: grafana
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: hera-namespace
  labels:
    k8s-app: alertmanager
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 9093
      nodePort: 32004
  selector:
    k8s-app: alertmanager

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: hera-namespace
spec:
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
      nodePort: 32005
  selector:
    app: prometheus
  type: NodePort