name: Build

on:
  push:
    branches: [ ehviewer_cn_sxj ]






jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew clean app:assembleDebug
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: ./app/build/outputs/apk/
