name: Build Installer

on:
  push:
    branches: [ aliucord ]













jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        path: src

    - name: Setup Flutter
      uses: subosito/flutter-action@d8687e6979e8ef66d2b2970e2c92c1d8e801d7bf # v2.4.0
      with:
        flutter-version: '3.0.0'

    - name: Build Installer
      run: |
        cd $GITHUB_WORKSPACE/src/installer
        echo "${{ secrets.keystore }}" | base64 -d > ../../keystore.jks
        echo "storePassword: ${{ secrets.keystorePassword }}" > android/key.properties
        echo "keyPassword: ${{ secrets.keyPassword }}" >> android/key.properties
        echo "keyAlias: Installer" >> android/key.properties
        echo "storeFile: ../../../../keystore.jks" >> android/key.properties
        
        versionName="${{ github.event.inputs.version }}"
        versionCode="${versionName//./}"
        flutter build apk --build-number "$versionCode" --build-name "$versionName"
        
        mv build/app/outputs/flutter-apk/app-release.apk ../../Installer-release.apk
        rm ../../keystore.jks
        rm android/key.properties

    - name: Release
      run: |
        cd $GITHUB_WORKSPACE/src
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        tag="${{ github.event.inputs.version }}"
        git tag "$tag"
        git push origin "$tag"
        gh release create "$tag" \
          --title "${{ github.event.inputs.title }}" \
          --notes "${{ github.event.inputs.description }}" \
          ../Installer-release.apk
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
