# 名称
name: Build and Push MySQL Docker Image

# 触发条件
on:
  push:
    branches: [ chatgpt-web-java ]













jobs:
  build:
    # 脚本运行在容器中镜像是 ubuntu-latest
    runs-on: ubuntu-latest

    # 定义任务中的步骤
    steps:
      # 从 Github 仓库中获取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 使用 Docker Buildkit 构建和推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile_mysql
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
        env:
          DOCKER_BUILDKIT: 1 # 启用BuildKit构建引擎
