name: No Response

# Both `issue_comment` and `scheduled` event types are required for this Action
# to work properly.
on:
  push:
    branches: [ newpipe ]










jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ github.token }}
          daysUntilClose: 14
          responseRequiredLabel: waiting for author
