name: Protect write-access files from being PR'd

on:
  push:
    branches: [ grasscutter ]












jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "This PR has been closed for modifying protected files. See `CONTRIBUTING.md` for more information."
